CREATE TABLE IF NOT EXISTS chile_communes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    commune VARCHAR(150) NOT NULL,
    city VARCHAR(150) NOT NULL,
    region VARCHAR(150) NOT NULL,
    UNIQUE KEY uniq_chile_communes_commune (commune),
    INDEX idx_chile_communes_city (city),
    INDEX idx_chile_communes_region (region)
);

CREATE TABLE IF NOT EXISTS regions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    UNIQUE KEY uniq_regions_name (name)
);

CREATE TABLE IF NOT EXISTS cities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    region_id INT NOT NULL,
    name VARCHAR(150) NOT NULL,
    UNIQUE KEY uniq_cities_region_name (region_id, name),
    INDEX idx_cities_name (name),
    FOREIGN KEY (region_id) REFERENCES regions(id)
);

CREATE TABLE IF NOT EXISTS communes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    city_id INT NOT NULL,
    name VARCHAR(150) NOT NULL,
    UNIQUE KEY uniq_communes_city_name (city_id, name),
    INDEX idx_communes_name (name),
    FOREIGN KEY (city_id) REFERENCES cities(id)
);

CREATE TABLE IF NOT EXISTS sii_activity_codes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    UNIQUE KEY uniq_sii_activity_code (code),
    INDEX idx_sii_activity_name (name)
);

SET @clients_activity_code := (
    SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'clients' AND COLUMN_NAME = 'activity_code'
);
SET @sql := IF(@clients_activity_code = 0, 'ALTER TABLE clients ADD COLUMN activity_code VARCHAR(50) NULL AFTER giro;', 'SELECT 1;');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @clients_commune := (
    SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'clients' AND COLUMN_NAME = 'commune'
);
SET @sql := IF(@clients_commune = 0, 'ALTER TABLE clients ADD COLUMN commune VARCHAR(120) NULL AFTER activity_code;', 'SELECT 1;');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @clients_city := (
    SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'clients' AND COLUMN_NAME = 'city'
);
SET @sql := IF(@clients_city = 0, 'ALTER TABLE clients ADD COLUMN city VARCHAR(120) NULL AFTER commune;', 'SELECT 1;');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

INSERT IGNORE INTO chile_communes (commune, city, region) VALUES
('Arica', 'Arica', 'Arica y Parinacota'),
('Camarones', 'Camarones', 'Arica y Parinacota'),
('Putre', 'Putre', 'Arica y Parinacota'),
('General Lagos', 'General Lagos', 'Arica y Parinacota'),
('Iquique', 'Iquique', 'Tarapacá'),
('Alto Hospicio', 'Alto Hospicio', 'Tarapacá'),
('Pozo Almonte', 'Pozo Almonte', 'Tarapacá'),
('Camiña', 'Camiña', 'Tarapacá'),
('Colchane', 'Colchane', 'Tarapacá'),
('Huara', 'Huara', 'Tarapacá'),
('Pica', 'Pica', 'Tarapacá'),
('Antofagasta', 'Antofagasta', 'Antofagasta'),
('Mejillones', 'Mejillones', 'Antofagasta'),
('Sierra Gorda', 'Sierra Gorda', 'Antofagasta'),
('Taltal', 'Taltal', 'Antofagasta'),
('Calama', 'Calama', 'Antofagasta'),
('Ollagüe', 'Ollagüe', 'Antofagasta'),
('San Pedro de Atacama', 'San Pedro de Atacama', 'Antofagasta'),
('Tocopilla', 'Tocopilla', 'Antofagasta'),
('María Elena', 'María Elena', 'Antofagasta'),
('Copiapó', 'Copiapó', 'Atacama'),
('Caldera', 'Caldera', 'Atacama'),
('Tierra Amarilla', 'Tierra Amarilla', 'Atacama'),
('Chañaral', 'Chañaral', 'Atacama'),
('Diego de Almagro', 'Diego de Almagro', 'Atacama'),
('Vallenar', 'Vallenar', 'Atacama'),
('Alto del Carmen', 'Alto del Carmen', 'Atacama'),
('Freirina', 'Freirina', 'Atacama'),
('Huasco', 'Huasco', 'Atacama'),
('La Serena', 'La Serena', 'Coquimbo'),
('Coquimbo', 'Coquimbo', 'Coquimbo'),
('Andacollo', 'Andacollo', 'Coquimbo'),
('La Higuera', 'La Higuera', 'Coquimbo'),
('Paiguano', 'Paiguano', 'Coquimbo'),
('Vicuña', 'Vicuña', 'Coquimbo'),
('Illapel', 'Illapel', 'Coquimbo'),
('Canela', 'Canela', 'Coquimbo'),
('Los Vilos', 'Los Vilos', 'Coquimbo'),
('Salamanca', 'Salamanca', 'Coquimbo'),
('Ovalle', 'Ovalle', 'Coquimbo'),
('Combarbalá', 'Combarbalá', 'Coquimbo'),
('Monte Patria', 'Monte Patria', 'Coquimbo'),
('Punitaqui', 'Punitaqui', 'Coquimbo'),
('Río Hurtado', 'Río Hurtado', 'Coquimbo'),
('Valparaíso', 'Valparaíso', 'Valparaíso'),
('Casablanca', 'Casablanca', 'Valparaíso'),
('Concón', 'Concón', 'Valparaíso'),
('Juan Fernández', 'Juan Fernández', 'Valparaíso'),
('Puchuncaví', 'Puchuncaví', 'Valparaíso'),
('Quintero', 'Quintero', 'Valparaíso'),
('Viña del Mar', 'Viña del Mar', 'Valparaíso'),
('Isla de Pascua', 'Isla de Pascua', 'Valparaíso'),
('Los Andes', 'Los Andes', 'Valparaíso'),
('Calle Larga', 'Calle Larga', 'Valparaíso'),
('Rinconada', 'Rinconada', 'Valparaíso'),
('San Esteban', 'San Esteban', 'Valparaíso'),
('La Ligua', 'La Ligua', 'Valparaíso'),
('Cabildo', 'Cabildo', 'Valparaíso'),
('Papudo', 'Papudo', 'Valparaíso'),
('Petorca', 'Petorca', 'Valparaíso'),
('Zapallar', 'Zapallar', 'Valparaíso'),
('Quillota', 'Quillota', 'Valparaíso'),
('La Calera', 'La Calera', 'Valparaíso'),
('Hijuelas', 'Hijuelas', 'Valparaíso'),
('La Cruz', 'La Cruz', 'Valparaíso'),
('Nogales', 'Nogales', 'Valparaíso'),
('San Antonio', 'San Antonio', 'Valparaíso'),
('Algarrobo', 'Algarrobo', 'Valparaíso'),
('Cartagena', 'Cartagena', 'Valparaíso'),
('El Quisco', 'El Quisco', 'Valparaíso'),
('El Tabo', 'El Tabo', 'Valparaíso'),
('Santo Domingo', 'Santo Domingo', 'Valparaíso'),
('San Felipe', 'San Felipe', 'Valparaíso'),
('Catemu', 'Catemu', 'Valparaíso'),
('Llaillay', 'Llaillay', 'Valparaíso'),
('Panquehue', 'Panquehue', 'Valparaíso'),
('Putaendo', 'Putaendo', 'Valparaíso'),
('Santa María', 'Santa María', 'Valparaíso'),
('Limache', 'Limache', 'Valparaíso'),
('Olmué', 'Olmué', 'Valparaíso'),
('Quilpué', 'Quilpué', 'Valparaíso'),
('Villa Alemana', 'Villa Alemana', 'Valparaíso'),
('Santiago', 'Santiago', 'Metropolitana de Santiago'),
('Cerrillos', 'Cerrillos', 'Metropolitana de Santiago'),
('Cerro Navia', 'Cerro Navia', 'Metropolitana de Santiago'),
('Conchalí', 'Conchalí', 'Metropolitana de Santiago'),
('El Bosque', 'El Bosque', 'Metropolitana de Santiago'),
('Estación Central', 'Estación Central', 'Metropolitana de Santiago'),
('Huechuraba', 'Huechuraba', 'Metropolitana de Santiago'),
('Independencia', 'Independencia', 'Metropolitana de Santiago'),
('La Cisterna', 'La Cisterna', 'Metropolitana de Santiago'),
('La Florida', 'La Florida', 'Metropolitana de Santiago'),
('La Granja', 'La Granja', 'Metropolitana de Santiago'),
('La Pintana', 'La Pintana', 'Metropolitana de Santiago'),
('La Reina', 'La Reina', 'Metropolitana de Santiago'),
('Las Condes', 'Las Condes', 'Metropolitana de Santiago'),
('Lo Barnechea', 'Lo Barnechea', 'Metropolitana de Santiago'),
('Lo Espejo', 'Lo Espejo', 'Metropolitana de Santiago'),
('Lo Prado', 'Lo Prado', 'Metropolitana de Santiago'),
('Macul', 'Macul', 'Metropolitana de Santiago'),
('Maipú', 'Maipú', 'Metropolitana de Santiago'),
('Ñuñoa', 'Ñuñoa', 'Metropolitana de Santiago'),
('Pedro Aguirre Cerda', 'Pedro Aguirre Cerda', 'Metropolitana de Santiago'),
('Peñalolén', 'Peñalolén', 'Metropolitana de Santiago'),
('Providencia', 'Providencia', 'Metropolitana de Santiago'),
('Pudahuel', 'Pudahuel', 'Metropolitana de Santiago'),
('Quilicura', 'Quilicura', 'Metropolitana de Santiago'),
('Quinta Normal', 'Quinta Normal', 'Metropolitana de Santiago'),
('Recoleta', 'Recoleta', 'Metropolitana de Santiago'),
('Renca', 'Renca', 'Metropolitana de Santiago'),
('San Joaquín', 'San Joaquín', 'Metropolitana de Santiago'),
('San Miguel', 'San Miguel', 'Metropolitana de Santiago'),
('San Ramón', 'San Ramón', 'Metropolitana de Santiago'),
('Vitacura', 'Vitacura', 'Metropolitana de Santiago'),
('Puente Alto', 'Puente Alto', 'Metropolitana de Santiago'),
('Pirque', 'Pirque', 'Metropolitana de Santiago'),
('San José de Maipo', 'San José de Maipo', 'Metropolitana de Santiago'),
('Colina', 'Colina', 'Metropolitana de Santiago'),
('Lampa', 'Lampa', 'Metropolitana de Santiago'),
('Tiltil', 'Tiltil', 'Metropolitana de Santiago'),
('San Bernardo', 'San Bernardo', 'Metropolitana de Santiago'),
('Buin', 'Buin', 'Metropolitana de Santiago'),
('Calera de Tango', 'Calera de Tango', 'Metropolitana de Santiago'),
('Paine', 'Paine', 'Metropolitana de Santiago'),
('Melipilla', 'Melipilla', 'Metropolitana de Santiago'),
('Alhué', 'Alhué', 'Metropolitana de Santiago'),
('Curacaví', 'Curacaví', 'Metropolitana de Santiago'),
('María Pinto', 'María Pinto', 'Metropolitana de Santiago'),
('San Pedro', 'San Pedro', 'Metropolitana de Santiago'),
('Talagante', 'Talagante', 'Metropolitana de Santiago'),
('El Monte', 'El Monte', 'Metropolitana de Santiago'),
('Isla de Maipo', 'Isla de Maipo', 'Metropolitana de Santiago'),
('Padre Hurtado', 'Padre Hurtado', 'Metropolitana de Santiago'),
('Peñaflor', 'Peñaflor', 'Metropolitana de Santiago'),
('Rancagua', 'Rancagua', 'Libertador General Bernardo O\'Higgins'),
('Codegua', 'Codegua', 'Libertador General Bernardo O\'Higgins'),
('Coinco', 'Coinco', 'Libertador General Bernardo O\'Higgins'),
('Coltauco', 'Coltauco', 'Libertador General Bernardo O\'Higgins'),
('Doñihue', 'Doñihue', 'Libertador General Bernardo O\'Higgins'),
('Graneros', 'Graneros', 'Libertador General Bernardo O\'Higgins'),
('Las Cabras', 'Las Cabras', 'Libertador General Bernardo O\'Higgins'),
('Machalí', 'Machalí', 'Libertador General Bernardo O\'Higgins'),
('Malloa', 'Malloa', 'Libertador General Bernardo O\'Higgins'),
('Mostazal', 'Mostazal', 'Libertador General Bernardo O\'Higgins'),
('Olivar', 'Olivar', 'Libertador General Bernardo O\'Higgins'),
('Peumo', 'Peumo', 'Libertador General Bernardo O\'Higgins'),
('Pichidegua', 'Pichidegua', 'Libertador General Bernardo O\'Higgins'),
('Quinta de Tilcoco', 'Quinta de Tilcoco', 'Libertador General Bernardo O\'Higgins'),
('Rengo', 'Rengo', 'Libertador General Bernardo O\'Higgins'),
('Requínoa', 'Requínoa', 'Libertador General Bernardo O\'Higgins'),
('San Vicente', 'San Vicente', 'Libertador General Bernardo O\'Higgins'),
('San Fernando', 'San Fernando', 'Libertador General Bernardo O\'Higgins'),
('Chimbarongo', 'Chimbarongo', 'Libertador General Bernardo O\'Higgins'),
('Lolol', 'Lolol', 'Libertador General Bernardo O\'Higgins'),
('Nancagua', 'Nancagua', 'Libertador General Bernardo O\'Higgins'),
('Palmilla', 'Palmilla', 'Libertador General Bernardo O\'Higgins'),
('Peralillo', 'Peralillo', 'Libertador General Bernardo O\'Higgins'),
('Placilla', 'Placilla', 'Libertador General Bernardo O\'Higgins'),
('Pumanque', 'Pumanque', 'Libertador General Bernardo O\'Higgins'),
('Santa Cruz', 'Santa Cruz', 'Libertador General Bernardo O\'Higgins'),
('Pichilemu', 'Pichilemu', 'Libertador General Bernardo O\'Higgins'),
('La Estrella', 'La Estrella', 'Libertador General Bernardo O\'Higgins'),
('Litueche', 'Litueche', 'Libertador General Bernardo O\'Higgins'),
('Marchihue', 'Marchihue', 'Libertador General Bernardo O\'Higgins'),
('Navidad', 'Navidad', 'Libertador General Bernardo O\'Higgins'),
('Paredones', 'Paredones', 'Libertador General Bernardo O\'Higgins'),
('Talca', 'Talca', 'Maule'),
('Constitución', 'Constitución', 'Maule'),
('Curepto', 'Curepto', 'Maule'),
('Empedrado', 'Empedrado', 'Maule'),
('Maule', 'Maule', 'Maule'),
('Pelarco', 'Pelarco', 'Maule'),
('Pencahue', 'Pencahue', 'Maule'),
('Río Claro', 'Río Claro', 'Maule'),
('San Clemente', 'San Clemente', 'Maule'),
('San Rafael', 'San Rafael', 'Maule'),
('Cauquenes', 'Cauquenes', 'Maule'),
('Chanco', 'Chanco', 'Maule'),
('Pelluhue', 'Pelluhue', 'Maule'),
('Curicó', 'Curicó', 'Maule'),
('Hualañé', 'Hualañé', 'Maule'),
('Licantén', 'Licantén', 'Maule'),
('Molina', 'Molina', 'Maule'),
('Rauco', 'Rauco', 'Maule'),
('Romeral', 'Romeral', 'Maule'),
('Sagrada Familia', 'Sagrada Familia', 'Maule'),
('Teno', 'Teno', 'Maule'),
('Vichuquén', 'Vichuquén', 'Maule'),
('Linares', 'Linares', 'Maule'),
('Colbún', 'Colbún', 'Maule'),
('Longaví', 'Longaví', 'Maule'),
('Parral', 'Parral', 'Maule'),
('Retiro', 'Retiro', 'Maule'),
('San Javier', 'San Javier', 'Maule'),
('Villa Alegre', 'Villa Alegre', 'Maule'),
('Yerbas Buenas', 'Yerbas Buenas', 'Maule'),
('Chillán', 'Chillán', 'Ñuble'),
('Bulnes', 'Bulnes', 'Ñuble'),
('Chillán Viejo', 'Chillán Viejo', 'Ñuble'),
('Cobquecura', 'Cobquecura', 'Ñuble'),
('Coelemu', 'Coelemu', 'Ñuble'),
('Coihueco', 'Coihueco', 'Ñuble'),
('El Carmen', 'El Carmen', 'Ñuble'),
('Ninhue', 'Ninhue', 'Ñuble'),
('Ñiquén', 'Ñiquén', 'Ñuble'),
('Pemuco', 'Pemuco', 'Ñuble'),
('Pinto', 'Pinto', 'Ñuble'),
('Portezuelo', 'Portezuelo', 'Ñuble'),
('Quillón', 'Quillón', 'Ñuble'),
('Quirihue', 'Quirihue', 'Ñuble'),
('Ránquil', 'Ránquil', 'Ñuble'),
('San Carlos', 'San Carlos', 'Ñuble'),
('San Fabián', 'San Fabián', 'Ñuble'),
('San Ignacio', 'San Ignacio', 'Ñuble'),
('San Nicolás', 'San Nicolás', 'Ñuble'),
('Trehuaco', 'Trehuaco', 'Ñuble'),
('Yungay', 'Yungay', 'Ñuble'),
('Concepción', 'Concepción', 'Biobío'),
('Coronel', 'Coronel', 'Biobío'),
('Chiguayante', 'Chiguayante', 'Biobío'),
('Florida', 'Florida', 'Biobío'),
('Hualqui', 'Hualqui', 'Biobío'),
('Lota', 'Lota', 'Biobío'),
('Penco', 'Penco', 'Biobío'),
('San Pedro de la Paz', 'San Pedro de la Paz', 'Biobío'),
('Santa Juana', 'Santa Juana', 'Biobío'),
('Talcahuano', 'Talcahuano', 'Biobío'),
('Tomé', 'Tomé', 'Biobío'),
('Lebu', 'Lebu', 'Biobío'),
('Arauco', 'Arauco', 'Biobío'),
('Cañete', 'Cañete', 'Biobío'),
('Contulmo', 'Contulmo', 'Biobío'),
('Curanilahue', 'Curanilahue', 'Biobío'),
('Los Álamos', 'Los Álamos', 'Biobío'),
('Tirúa', 'Tirúa', 'Biobío'),
('Los Ángeles', 'Los Ángeles', 'Biobío'),
('Antuco', 'Antuco', 'Biobío'),
('Cabrero', 'Cabrero', 'Biobío'),
('Laja', 'Laja', 'Biobío'),
('Mulchén', 'Mulchén', 'Biobío'),
('Nacimiento', 'Nacimiento', 'Biobío'),
('Negrete', 'Negrete', 'Biobío'),
('Quilaco', 'Quilaco', 'Biobío'),
('Quilleco', 'Quilleco', 'Biobío'),
('San Rosendo', 'San Rosendo', 'Biobío'),
('Santa Bárbara', 'Santa Bárbara', 'Biobío'),
('Tucapel', 'Tucapel', 'Biobío'),
('Yumbel', 'Yumbel', 'Biobío'),
('Alto Biobío', 'Alto Biobío', 'Biobío'),
('Temuco', 'Temuco', 'Araucanía'),
('Carahue', 'Carahue', 'Araucanía'),
('Cunco', 'Cunco', 'Araucanía'),
('Curarrehue', 'Curarrehue', 'Araucanía'),
('Freire', 'Freire', 'Araucanía'),
('Galvarino', 'Galvarino', 'Araucanía'),
('Gorbea', 'Gorbea', 'Araucanía'),
('Lautaro', 'Lautaro', 'Araucanía'),
('Loncoche', 'Loncoche', 'Araucanía'),
('Melipeuco', 'Melipeuco', 'Araucanía'),
('Nueva Imperial', 'Nueva Imperial', 'Araucanía'),
('Padre Las Casas', 'Padre Las Casas', 'Araucanía'),
('Perquenco', 'Perquenco', 'Araucanía'),
('Pitrufquén', 'Pitrufquén', 'Araucanía'),
('Pucón', 'Pucón', 'Araucanía'),
('Saavedra', 'Saavedra', 'Araucanía'),
('Teodoro Schmidt', 'Teodoro Schmidt', 'Araucanía'),
('Toltén', 'Toltén', 'Araucanía'),
('Vilcún', 'Vilcún', 'Araucanía'),
('Villarrica', 'Villarrica', 'Araucanía'),
('Cholchol', 'Cholchol', 'Araucanía'),
('Angol', 'Angol', 'Araucanía'),
('Collipulli', 'Collipulli', 'Araucanía'),
('Curacautín', 'Curacautín', 'Araucanía'),
('Ercilla', 'Ercilla', 'Araucanía'),
('Lonquimay', 'Lonquimay', 'Araucanía'),
('Los Sauces', 'Los Sauces', 'Araucanía'),
('Lumaco', 'Lumaco', 'Araucanía'),
('Purén', 'Purén', 'Araucanía'),
('Renaico', 'Renaico', 'Araucanía'),
('Traiguén', 'Traiguén', 'Araucanía'),
('Victoria', 'Victoria', 'Araucanía'),
('Valdivia', 'Valdivia', 'Los Ríos'),
('Corral', 'Corral', 'Los Ríos'),
('Lanco', 'Lanco', 'Los Ríos'),
('Los Lagos', 'Los Lagos', 'Los Ríos'),
('Máfil', 'Máfil', 'Los Ríos'),
('Mariquina', 'Mariquina', 'Los Ríos'),
('Paillaco', 'Paillaco', 'Los Ríos'),
('Panguipulli', 'Panguipulli', 'Los Ríos'),
('La Unión', 'La Unión', 'Los Ríos'),
('Futrono', 'Futrono', 'Los Ríos'),
('Lago Ranco', 'Lago Ranco', 'Los Ríos'),
('Río Bueno', 'Río Bueno', 'Los Ríos'),
('Puerto Montt', 'Puerto Montt', 'Los Lagos'),
('Calbuco', 'Calbuco', 'Los Lagos'),
('Cochamó', 'Cochamó', 'Los Lagos'),
('Fresia', 'Fresia', 'Los Lagos'),
('Frutillar', 'Frutillar', 'Los Lagos'),
('Los Muermos', 'Los Muermos', 'Los Lagos'),
('Llanquihue', 'Llanquihue', 'Los Lagos'),
('Maullín', 'Maullín', 'Los Lagos'),
('Puerto Varas', 'Puerto Varas', 'Los Lagos'),
('Castro', 'Castro', 'Los Lagos'),
('Ancud', 'Ancud', 'Los Lagos'),
('Chonchi', 'Chonchi', 'Los Lagos'),
('Curaco de Vélez', 'Curaco de Vélez', 'Los Lagos'),
('Dalcahue', 'Dalcahue', 'Los Lagos'),
('Puqueldón', 'Puqueldón', 'Los Lagos'),
('Queilén', 'Queilén', 'Los Lagos'),
('Quellón', 'Quellón', 'Los Lagos'),
('Quemchi', 'Quemchi', 'Los Lagos'),
('Quinchao', 'Quinchao', 'Los Lagos'),
('Osorno', 'Osorno', 'Los Lagos'),
('Puerto Octay', 'Puerto Octay', 'Los Lagos'),
('Purranque', 'Purranque', 'Los Lagos'),
('Puyehue', 'Puyehue', 'Los Lagos'),
('Río Negro', 'Río Negro', 'Los Lagos'),
('San Juan de la Costa', 'San Juan de la Costa', 'Los Lagos'),
('San Pablo', 'San Pablo', 'Los Lagos'),
('Chaitén', 'Chaitén', 'Los Lagos'),
('Futaleufú', 'Futaleufú', 'Los Lagos'),
('Hualaihué', 'Hualaihué', 'Los Lagos'),
('Palena', 'Palena', 'Los Lagos'),
('Coyhaique', 'Coyhaique', 'Aysén del General Carlos Ibáñez del Campo'),
('Lago Verde', 'Lago Verde', 'Aysén del General Carlos Ibáñez del Campo'),
('Aysén', 'Aysén', 'Aysén del General Carlos Ibáñez del Campo'),
('Cisnes', 'Cisnes', 'Aysén del General Carlos Ibáñez del Campo'),
('Guaitecas', 'Guaitecas', 'Aysén del General Carlos Ibáñez del Campo'),
('Cochrane', 'Cochrane', 'Aysén del General Carlos Ibáñez del Campo'),
('O\'Higgins', 'O\'Higgins', 'Aysén del General Carlos Ibáñez del Campo'),
('Tortel', 'Tortel', 'Aysén del General Carlos Ibáñez del Campo'),
('Chile Chico', 'Chile Chico', 'Aysén del General Carlos Ibáñez del Campo'),
('Río Ibáñez', 'Río Ibáñez', 'Aysén del General Carlos Ibáñez del Campo'),
('Punta Arenas', 'Punta Arenas', 'Magallanes y de la Antártica Chilena'),
('Laguna Blanca', 'Laguna Blanca', 'Magallanes y de la Antártica Chilena'),
('Río Verde', 'Río Verde', 'Magallanes y de la Antártica Chilena'),
('San Gregorio', 'San Gregorio', 'Magallanes y de la Antártica Chilena'),
('Cabo de Hornos', 'Cabo de Hornos', 'Magallanes y de la Antártica Chilena'),
('Antártica', 'Antártica', 'Magallanes y de la Antártica Chilena'),
('Porvenir', 'Porvenir', 'Magallanes y de la Antártica Chilena'),
('Primavera', 'Primavera', 'Magallanes y de la Antártica Chilena'),
('Timaukel', 'Timaukel', 'Magallanes y de la Antártica Chilena'),
('Natales', 'Natales', 'Magallanes y de la Antártica Chilena'),
('Torres del Paine', 'Torres del Paine', 'Magallanes y de la Antártica Chilena');

INSERT IGNORE INTO regions (name)
SELECT DISTINCT region
FROM chile_communes
ORDER BY region;

INSERT IGNORE INTO cities (name, region_id)
SELECT DISTINCT chile_communes.city, regions.id
FROM chile_communes
JOIN regions ON regions.name = chile_communes.region
ORDER BY chile_communes.city;

INSERT IGNORE INTO communes (name, city_id)
SELECT chile_communes.commune, cities.id
FROM chile_communes
JOIN regions ON regions.name = chile_communes.region
JOIN cities ON cities.name = chile_communes.city AND cities.region_id = regions.id
ORDER BY chile_communes.commune;

INSERT IGNORE INTO sii_activity_codes (code, name) VALUES
('011111', 'Cultivo de trigo'),
('011112', 'Cultivo de maíz'),
('011113', 'Cultivo de arroz'),
('011119', 'Otros cultivos de cereales'),
('011120', 'Cultivo de legumbres y semillas oleaginosas'),
('011131', 'Cultivo de papa'),
('011139', 'Cultivo de raíces y tubérculos n.c.p.'),
('011200', 'Cultivo de hortalizas'),
('011300', 'Cultivo de frutas'),
('011400', 'Cultivo de uvas'),
('011500', 'Cultivo de frutos oleaginosos'),
('011600', 'Cultivo de plantas para preparar bebidas'),
('011900', 'Otros cultivos permanentes'),
('012110', 'Cultivo de flores'),
('012120', 'Cultivo de plantas vivas y productos de vivero'),
('012130', 'Producción de semillas'),
('012140', 'Producción de plántulas'),
('012200', 'Producción de hongos y trufas'),
('012900', 'Otros cultivos no permanentes n.c.p.'),
('013000', 'Cultivo de plantas de vivero'),
('014111', 'Cría de ganado bovino'),
('014112', 'Engorda de ganado bovino'),
('014120', 'Cría de ganado equino'),
('014130', 'Cría de ovinos y caprinos'),
('014141', 'Cría de porcinos'),
('014200', 'Cría de aves de corral'),
('014300', 'Cría de otros animales'),
('014400', 'Producción de leche'),
('014500', 'Producción de huevos'),
('014600', 'Apicultura'),
('014900', 'Otras actividades de apoyo a la ganadería'),
('016100', 'Actividades de apoyo a la agricultura'),
('016200', 'Actividades de apoyo a la ganadería'),
('016300', 'Actividades posteriores a la cosecha'),
('016400', 'Tratamiento de semillas para propagación'),
('021000', 'Silvicultura'),
('022000', 'Extracción de madera'),
('023000', 'Recolección de productos forestales'),
('024000', 'Servicios de apoyo a la silvicultura'),
('031100', 'Pesca marítima'),
('031200', 'Pesca de agua dulce'),
('032100', 'Acuicultura marítima'),
('032200', 'Acuicultura de agua dulce'),
('051000', 'Extracción de carbón de piedra'),
('052000', 'Extracción de lignito'),
('061000', 'Extracción de petróleo crudo'),
('062000', 'Extracción de gas natural'),
('071000', 'Extracción de minerales de hierro'),
('072100', 'Extracción de minerales de uranio y torio'),
('072910', 'Extracción de cobre'),
('072920', 'Extracción de otros minerales metálicos no ferrosos'),
('081000', 'Extracción de piedra, arena y arcilla'),
('089100', 'Extracción de minerales para productos químicos'),
('089200', 'Extracción de turba'),
('089300', 'Extracción de sal'),
('089900', 'Otras actividades de explotación de minas y canteras'),
('101010', 'Elaboración y conservación de carne'),
('101020', 'Elaboración y conservación de productos de la pesca'),
('101030', 'Elaboración y conservación de frutas, legumbres y hortalizas'),
('101040', 'Elaboración de aceites y grasas'),
('101050', 'Elaboración de productos lácteos'),
('101060', 'Elaboración de productos de molinería'),
('101070', 'Elaboración de almidones y productos derivados'),
('101080', 'Elaboración de productos de panadería'),
('101090', 'Elaboración de otros productos alimenticios'),
('102000', 'Elaboración de alimentos preparados para animales'),
('110100', 'Destilación de bebidas alcohólicas'),
('110200', 'Elaboración de vinos'),
('110300', 'Elaboración de cervezas'),
('110400', 'Elaboración de bebidas no alcohólicas'),
('120000', 'Elaboración de productos de tabaco'),
('131100', 'Preparación e hilatura de fibras textiles'),
('131200', 'Tejeduría de productos textiles'),
('131300', 'Acabado de productos textiles'),
('139100', 'Fabricación de tejidos de punto'),
('139200', 'Fabricación de otros productos textiles'),
('141000', 'Confección de prendas de vestir'),
('142000', 'Fabricación de artículos de piel'),
('143000', 'Fabricación de prendas de vestir de punto'),
('151100', 'Curtido y adobo de cuero'),
('151200', 'Fabricación de calzado'),
('152000', 'Fabricación de artículos de cuero'),
('161000', 'Aserrado y cepillado de madera'),
('162100', 'Fabricación de productos de madera'),
('170110', 'Fabricación de celulosa'),
('170120', 'Fabricación de papel y cartón'),
('170200', 'Fabricación de envases de papel'),
('181100', 'Impresión'),
('181200', 'Servicios relacionados con la impresión'),
('182000', 'Reproducción de soportes grabados'),
('191000', 'Fabricación de productos de hornos de coque'),
('192000', 'Fabricación de productos de la refinación del petróleo'),
('201100', 'Fabricación de sustancias químicas básicas'),
('201200', 'Fabricación de fertilizantes'),
('201300', 'Fabricación de plásticos y caucho sintético'),
('202100', 'Fabricación de plaguicidas'),
('202200', 'Fabricación de pinturas'),
('202300', 'Fabricación de jabones y detergentes'),
('202900', 'Fabricación de otros productos químicos'),
('210000', 'Fabricación de productos farmacéuticos'),
('221100', 'Fabricación de neumáticos'),
('221900', 'Fabricación de otros productos de caucho'),
('222000', 'Fabricación de productos de plástico'),
('231000', 'Fabricación de vidrio'),
('239100', 'Fabricación de productos de cerámica'),
('239200', 'Fabricación de productos refractarios'),
('239300', 'Fabricación de productos de arcilla'),
('239400', 'Fabricación de cemento'),
('239500', 'Fabricación de yeso'),
('239600', 'Fabricación de productos de hormigón'),
('239900', 'Fabricación de otros productos minerales no metálicos'),
('241000', 'Industrias básicas de hierro y acero'),
('242000', 'Industrias básicas de metales preciosos y no ferrosos'),
('243100', 'Fundición de hierro y acero'),
('243200', 'Fundición de metales no ferrosos'),
('251100', 'Fabricación de productos metálicos'),
('251200', 'Fabricación de tanques y depósitos'),
('252000', 'Fabricación de armas y municiones'),
('259100', 'Forja y estampado de metales'),
('259200', 'Tratamiento y revestimiento de metales'),
('259300', 'Fabricación de artículos de ferretería'),
('259900', 'Fabricación de otros productos elaborados de metal'),
('261000', 'Fabricación de componentes electrónicos'),
('262000', 'Fabricación de computadores y periféricos'),
('263000', 'Fabricación de equipos de comunicación'),
('264000', 'Fabricación de aparatos electrónicos de consumo'),
('265100', 'Fabricación de instrumentos de medición'),
('265200', 'Fabricación de relojes'),
('266000', 'Fabricación de equipos de radiación'),
('267000', 'Fabricación de instrumentos ópticos'),
('268000', 'Fabricación de soportes magnéticos y ópticos'),
('271000', 'Fabricación de motores eléctricos'),
('272000', 'Fabricación de pilas y baterías'),
('273100', 'Fabricación de cables de fibra óptica'),
('273200', 'Fabricación de cables'),
('273300', 'Fabricación de dispositivos de cableado'),
('274000', 'Fabricación de equipos de iluminación'),
('275000', 'Fabricación de aparatos de uso doméstico'),
('279000', 'Fabricación de otros equipos eléctricos'),
('281100', 'Fabricación de motores y turbinas'),
('281200', 'Fabricación de bombas y compresores'),
('281300', 'Fabricación de grifos y válvulas'),
('281400', 'Fabricación de cojinetes y engranajes'),
('281500', 'Fabricación de hornos y quemadores'),
('281600', 'Fabricación de equipos de elevación'),
('281700', 'Fabricación de maquinaria para la construcción'),
('281800', 'Fabricación de maquinaria para la agricultura'),
('281900', 'Fabricación de maquinaria de uso general'),
('282100', 'Fabricación de maquinaria para metalurgia'),
('282200', 'Fabricación de maquinaria para minería'),
('282300', 'Fabricación de maquinaria para industria alimentaria'),
('282400', 'Fabricación de maquinaria para la industria textil'),
('282500', 'Fabricación de maquinaria para la industria del papel'),
('282900', 'Fabricación de otras maquinarias especiales'),
('291000', 'Fabricación de vehículos automotores'),
('292000', 'Fabricación de carrocerías y remolques'),
('293000', 'Fabricación de partes y piezas de vehículos'),
('301100', 'Construcción de buques'),
('301200', 'Construcción de embarcaciones de recreo'),
('302000', 'Fabricación de locomotoras y material rodante'),
('303000', 'Fabricación de aeronaves'),
('304000', 'Fabricación de vehículos militares'),
('309100', 'Fabricación de motocicletas'),
('309200', 'Fabricación de bicicletas'),
('309900', 'Fabricación de otros equipos de transporte'),
('310000', 'Fabricación de muebles'),
('321100', 'Fabricación de joyas'),
('321200', 'Fabricación de bisutería'),
('322000', 'Fabricación de instrumentos musicales'),
('323000', 'Fabricación de artículos deportivos'),
('324000', 'Fabricación de juegos y juguetes'),
('325000', 'Fabricación de instrumentos médicos'),
('329000', 'Otras industrias manufactureras n.c.p.'),
('331100', 'Reparación de productos metálicos'),
('331200', 'Reparación de maquinaria'),
('331300', 'Reparación de equipos electrónicos'),
('331400', 'Reparación de equipos eléctricos'),
('331500', 'Reparación de equipos de transporte'),
('331900', 'Reparación de otros equipos'),
('332000', 'Instalación de maquinaria y equipos'),
('351000', 'Generación de energía eléctrica'),
('352000', 'Transmisión de energía eléctrica'),
('353000', 'Distribución de energía eléctrica'),
('360000', 'Captación y distribución de agua'),
('370000', 'Evacuación de aguas residuales'),
('381100', 'Recolección de desechos'),
('381200', 'Tratamiento y eliminación de desechos'),
('382100', 'Recuperación de materiales'),
('390000', 'Actividades de descontaminación'),
('410010', 'Construcción de edificios'),
('410020', 'Construcción de viviendas'),
('421000', 'Construcción de carreteras'),
('422000', 'Construcción de proyectos de servicio público'),
('429000', 'Construcción de otras obras de ingeniería'),
('431100', 'Demolición'),
('431200', 'Preparación del terreno'),
('432100', 'Instalación eléctrica'),
('432200', 'Instalaciones de gas y calefacción'),
('432900', 'Otras instalaciones para obras de construcción'),
('433000', 'Terminación y acabado de edificios'),
('439000', 'Otras actividades especializadas de construcción'),
('451001', 'Venta de vehículos automotores'),
('452001', 'Mantenimiento y reparación de vehículos automotores'),
('453000', 'Venta de partes y piezas para vehículos'),
('454000', 'Venta de motocicletas y accesorios'),
('461000', 'Venta al por mayor a cambio de una retribución'),
('462000', 'Venta al por mayor de materias primas agropecuarias'),
('463000', 'Venta al por mayor de alimentos'),
('464100', 'Venta al por mayor de textiles'),
('464200', 'Venta al por mayor de prendas de vestir'),
('464300', 'Venta al por mayor de calzado'),
('464901', 'Venta al por mayor de maquinaria'),
('464902', 'Venta al por mayor de artículos eléctricos'),
('464903', 'Venta al por mayor de productos farmacéuticos'),
('464904', 'Venta al por mayor de combustibles'),
('464905', 'Venta al por mayor de materiales de construcción'),
('464906', 'Venta al por mayor de metales'),
('464907', 'Venta al por mayor de madera'),
('464908', 'Venta al por mayor de equipos médicos'),
('464909', 'Venta al por mayor de otros productos'),
('465100', 'Venta al por mayor de computadores'),
('465200', 'Venta al por mayor de equipos de telecomunicaciones'),
('465300', 'Venta al por mayor de equipos electrónicos'),
('466100', 'Venta al por mayor de maquinaria agrícola'),
('466200', 'Venta al por mayor de maquinaria para la minería'),
('466300', 'Venta al por mayor de maquinaria para la construcción'),
('466901', 'Venta al por mayor de otros tipos de maquinaria'),
('466902', 'Venta al por mayor de vehículos'),
('466903', 'Venta al por mayor de equipos de transporte'),
('466904', 'Venta al por mayor de productos químicos'),
('466909', 'Venta al por mayor de otros productos'),
('469000', 'Venta al por mayor no especializada'),
('471100', 'Venta al por menor en comercios no especializados'),
('471900', 'Venta al por menor en otros comercios no especializados'),
('472100', 'Venta al por menor de alimentos'),
('472200', 'Venta al por menor de bebidas'),
('472300', 'Venta al por menor de tabaco'),
('472400', 'Venta al por menor de combustibles'),
('472500', 'Venta al por menor de textiles'),
('472600', 'Venta al por menor de prendas de vestir'),
('472700', 'Venta al por menor de calzado'),
('472900', 'Venta al por menor de otros productos'),
('473000', 'Venta al por menor de combustibles para vehículos'),
('474100', 'Venta al por menor de computadores'),
('474200', 'Venta al por menor de equipos de telecomunicaciones'),
('474300', 'Venta al por menor de equipos electrónicos'),
('475100', 'Venta al por menor de textiles'),
('475200', 'Venta al por menor de ferretería'),
('475900', 'Venta al por menor de otros productos en comercios especializados'),
('476100', 'Venta al por menor de libros'),
('476200', 'Venta al por menor de periódicos'),
('476300', 'Venta al por menor de productos culturales'),
('476400', 'Venta al por menor de aparatos electrónicos'),
('476500', 'Venta al por menor de música'),
('477100', 'Venta al por menor de prendas de vestir'),
('477200', 'Venta al por menor de calzado'),
('477300', 'Venta al por menor de productos farmacéuticos'),
('477400', 'Venta al por menor de productos de cosmética'),
('477500', 'Venta al por menor de productos médicos'),
('477600', 'Venta al por menor de artículos deportivos'),
('477700', 'Venta al por menor de artículos recreativos'),
('477800', 'Venta al por menor de otros productos en comercios especializados'),
('478100', 'Venta al por menor en puestos de alimentos'),
('478200', 'Venta al por menor en puestos de textiles'),
('478900', 'Venta al por menor en otros puestos'),
('479100', 'Venta al por menor por internet'),
('479900', 'Venta al por menor por otros medios'),
('491100', 'Transporte interurbano de pasajeros por ferrocarril'),
('491200', 'Transporte de carga por ferrocarril'),
('492100', 'Transporte urbano de pasajeros'),
('492200', 'Transporte interurbano de pasajeros'),
('492300', 'Transporte de carga por carretera'),
('493000', 'Transporte por oleoducto'),
('501100', 'Transporte marítimo de pasajeros'),
('501200', 'Transporte marítimo de carga'),
('502100', 'Transporte fluvial de pasajeros'),
('502200', 'Transporte fluvial de carga'),
('511000', 'Transporte aéreo de pasajeros'),
('512000', 'Transporte aéreo de carga'),
('521000', 'Depósito y almacenamiento'),
('522100', 'Servicios auxiliares de transporte'),
('522200', 'Servicios auxiliares de transporte marítimo'),
('522300', 'Servicios auxiliares de transporte aéreo'),
('522400', 'Manipulación de carga'),
('522900', 'Otras actividades de apoyo al transporte'),
('531000', 'Actividades de correo'),
('532000', 'Actividades de mensajería'),
('551000', 'Alojamiento'),
('552000', 'Actividades de campamento'),
('559000', 'Otros tipos de alojamiento'),
('561000', 'Restaurantes y servicios de comida'),
('562000', 'Servicios de catering'),
('563000', 'Actividades de bebidas'),
('581100', 'Edición de libros'),
('581200', 'Edición de periódicos'),
('581300', 'Edición de revistas'),
('581900', 'Otras actividades de edición'),
('582000', 'Edición de programas informáticos'),
('591100', 'Producción de películas'),
('591200', 'Postproducción'),
('591300', 'Distribución de películas'),
('591400', 'Proyección de películas'),
('592000', 'Actividades de grabación sonora'),
('601000', 'Transmisión radial'),
('602000', 'Programación televisiva'),
('611000', 'Telecomunicaciones'),
('612000', 'Telecomunicaciones inalámbricas'),
('613000', 'Telecomunicaciones por satélite'),
('619000', 'Otras telecomunicaciones'),
('620100', 'Actividades de programación informática'),
('620200', 'Consultoría de informática'),
('620300', 'Gestión de instalaciones informáticas'),
('620900', 'Otras actividades de tecnología de la información'),
('631100', 'Procesamiento de datos'),
('631200', 'Portales web'),
('639100', 'Actividades de agencias de noticias'),
('639900', 'Otras actividades de servicios de información'),
('641100', 'Banca central'),
('641900', 'Otros servicios de intermediación monetaria'),
('642000', 'Actividades de sociedades de cartera'),
('643000', 'Fondos y sociedades de inversión'),
('649100', 'Arrendamiento financiero'),
('649200', 'Otros servicios financieros'),
('649300', 'Financiamiento de consumo'),
('649900', 'Otros servicios financieros n.c.p.'),
('651100', 'Seguros'),
('651200', 'Reaseguros'),
('652000', 'Planes de pensiones'),
('653000', 'Servicios auxiliares de seguros'),
('661100', 'Administración de mercados financieros'),
('661200', 'Corretaje de valores'),
('661900', 'Otras actividades auxiliares de servicios financieros'),
('662100', 'Evaluación de riesgos'),
('662200', 'Corretaje de seguros'),
('662900', 'Otras actividades auxiliares de seguros'),
('663000', 'Administración de fondos'),
('681000', 'Actividades inmobiliarias'),
('682000', 'Alquiler de bienes inmuebles'),
('691000', 'Actividades jurídicas'),
('692000', 'Actividades de contabilidad'),
('701000', 'Actividades de oficinas principales'),
('702000', 'Actividades de consultoría de gestión'),
('711000', 'Actividades de arquitectura'),
('712000', 'Ensayos y análisis técnicos'),
('721000', 'Investigación y desarrollo experimental en ciencias naturales'),
('722000', 'Investigación y desarrollo experimental en ciencias sociales'),
('731000', 'Publicidad'),
('732000', 'Investigación de mercados'),
('741000', 'Actividades de diseño especializado'),
('742000', 'Actividades de fotografía'),
('749000', 'Otras actividades profesionales'),
('750000', 'Actividades veterinarias'),
('771000', 'Alquiler de vehículos'),
('772100', 'Alquiler de artículos recreativos'),
('772200', 'Alquiler de videos'),
('772900', 'Alquiler de otros bienes'),
('773000', 'Alquiler de maquinaria y equipo'),
('774000', 'Arrendamiento de propiedad intelectual'),
('781000', 'Actividades de empleo'),
('782000', 'Actividades de agencias de empleo'),
('783000', 'Otras actividades de suministro de recursos humanos'),
('791100', 'Actividades de agencias de viaje'),
('791200', 'Actividades de operadores turísticos'),
('799000', 'Otros servicios de reservas'),
('801000', 'Actividades de seguridad privada'),
('802000', 'Actividades de servicios de seguridad'),
('803000', 'Investigaciones'),
('811000', 'Actividades de limpieza'),
('812100', 'Limpieza general de edificios'),
('812900', 'Otras actividades de limpieza'),
('813000', 'Servicios de paisajismo'),
('821100', 'Actividades administrativas'),
('821900', 'Servicios de apoyo a oficinas'),
('822000', 'Actividades de call center'),
('823000', 'Organización de convenciones'),
('829100', 'Agencias de cobranza'),
('829900', 'Otros servicios de apoyo a empresas'),
('841100', 'Administración pública'),
('842100', 'Relaciones exteriores'),
('842200', 'Defensa'),
('842300', 'Orden público'),
('843000', 'Seguridad social'),
('851000', 'Enseñanza preescolar'),
('852100', 'Enseñanza primaria'),
('852200', 'Enseñanza secundaria'),
('853100', 'Educación superior'),
('853200', 'Educación técnica'),
('854100', 'Educación deportiva'),
('854200', 'Educación cultural'),
('854900', 'Otras actividades de enseñanza'),
('855000', 'Servicios de apoyo a la enseñanza'),
('861000', 'Actividades de hospitales'),
('862000', 'Actividades médicas y odontológicas'),
('869000', 'Otras actividades de atención de la salud'),
('871000', 'Instituciones de atención de salud'),
('872000', 'Atención a personas con discapacidad'),
('873000', 'Atención a personas mayores'),
('879000', 'Otras actividades de asistencia social'),
('881000', 'Actividades de servicios sociales'),
('889000', 'Otros servicios sociales'),
('900000', 'Actividades creativas y artísticas'),
('910100', 'Actividades de bibliotecas'),
('910200', 'Actividades de museos'),
('910300', 'Actividades de jardines botánicos'),
('920000', 'Actividades de juegos de azar'),
('931100', 'Actividades deportivas'),
('931200', 'Actividades de clubes deportivos'),
('931900', 'Otras actividades deportivas'),
('932100', 'Parques de atracciones'),
('932900', 'Otras actividades de entretenimiento'),
('941100', 'Actividades de organizaciones empresariales'),
('941200', 'Actividades de organizaciones profesionales'),
('942000', 'Actividades de sindicatos'),
('949100', 'Actividades de organizaciones religiosas'),
('949200', 'Actividades de organizaciones políticas'),
('949900', 'Otras actividades asociativas'),
('951100', 'Reparación de computadores'),
('951200', 'Reparación de equipos de comunicación'),
('952100', 'Reparación de aparatos electrónicos'),
('952200', 'Reparación de electrodomésticos'),
('952300', 'Reparación de calzado y artículos de cuero'),
('952400', 'Reparación de muebles'),
('952900', 'Reparación de otros bienes'),
('960100', 'Lavado y limpieza de vehículos'),
('960200', 'Peluquería y otros tratamientos de belleza'),
('960300', 'Pompas fúnebres'),
('960900', 'Otras actividades de servicios personales');
